# Generated by Django 5.1.3 on 2025-03-26 05:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_rating_project'),
        ('skills', '0002_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='domain',
            field=models.ManyToManyField(to='skills.domain'),
        ),
        migrations.AlterUniqueTogether(
            name='savedproject',
            unique_together={('user', 'project')},
        ),
    ]
